export const IPC = {
  VIEWS_SET_BOUNDS: 'views:setBounds',
  VIEWS_RELOAD: 'views:reload',
  VIEWS_FOCUS: 'views:focus',
  VIEWS_OPEN_DEVTOOLS: 'views:openDevTools',
  VIEWS_LOGIN: 'views:login',
  BROADCAST_SEND: 'broadcast:send',
  SERVICE_STATUS: 'service:status',
  IMPORT_CHROME_COOKIES: 'import:chromeCookies',
  CDP_LOGIN: 'cdp:login',
  SERVICE_RESPONSE: 'service:response',
  WIN_MINIMIZE: 'win:minimize',
  WIN_MAXIMIZE: 'win:maximize',
  WIN_CLOSE: 'win:close',
  WIN_IS_MAXIMIZED: 'win:isMaximized',
  SKILLS_LIST: 'skills:list',
  SKILLS_READ: 'skills:read',
  SKILLS_OPEN_DIR: 'skills:openDir',
  SKILLS_CREATE: 'skills:create',
  SERVICE_SET_MODEL: 'service:setModel',
  VIEWS_NEW_CHAT: 'views:newChat',
} as const
